// Landlord testimonials, approved by each landlord on 15 September 2026.
// Shown as first name, what they own and where. Pages include them with
// <!-- testimonials: 1, 4, 12 --> or <!-- testimonials: all -->.
export const testimonials = [
  { id: 1, name: "John", who: "one flat in Wolverhampton, landlord since 2013", text: "I bought my first flat to let in Wolverhampton and had no idea how much there was to get wrong. Property Sauce sorted the gas and electrical certificates, the deposit, the tenancy agreement and the tenant before I had finished worrying about any of it. The rent lands in my account every month with a statement, and I can see everything about the flat in the portal whenever I like. I would not do it any other way now." },
  { id: 2, name: "Ahmed", who: "three flats in Croydon", text: "I have three flats in Croydon and used to spend my evenings chasing rent and contractors. Property Sauce took the whole lot on. Repairs get reported by the tenants online and are dealt with without me hearing about them unless a decision is needed, the certificates are renewed before they run out, and the portal scores every flat so I can see at a glance which one needs attention. My time is my own again." },
  { id: 3, name: "Jason", who: "two properties in Leyton, living in Cyprus", text: "I live in Cyprus and cannot be there when a boiler fails or a tenant leaves. Property Sauce runs my two properties in Leyton as if I were round the corner. Everything is in the portal: statements, certificates, the tenancy agreements, even the repair tickets with the contractor's notes. I sign in from a different time zone and it is all there. That is what I am paying for, and it is worth it." },
  { id: 4, name: "Sally", who: "one house in Chingford", text: "I never planned to be a landlord. I inherited my mother's house in Chingford and could not face selling it. Property Sauce found a good tenant within three weeks, dealt with the paperwork I did not understand, and now send me a statement every month. When the tenant reported a leak at nine at night, it was logged and a plumber was booked before I had even read the email. It has turned something I dreaded into an easy income." },
  { id: 5, name: "Peter", who: "two properties in south east London", text: "I moved two properties to Property Sauce from an agent who had stopped answering the phone. The difference was immediate. Within the first month they found two certificates that had lapsed without my knowing, renewed them, and set up the portal so I could see the whole portfolio in one place. The rent statements are clear and on time. I should have moved years ago." },
  { id: 6, name: "Trevor", who: "freeholder of a block of twelve flats in Blackpool", text: "I own the freehold of a block of twelve flats in Blackpool and Property Sauce look after the building for me: service charges, the communal repairs, the fire risk assessment, the insurance renewal and the leaseholders' questions. The accounts are straightforward and the leaseholders get answers the same day. Running a block is thankless work and they make it look easy." },
  { id: 7, name: "Mandy", who: "manager, 55 residential units in Cramlington", text: "Our company holds fifty-five residential units across Cramlington and needs an agent that reports properly. Property Sauce give us a portfolio dashboard, monthly statements per property, a compliance position we can show our board, and a maintenance record for every unit. They understand that we need the paperwork right as much as the rent collected. Professional, organised and easy to deal with." },
  { id: 8, name: "Eddie", who: "six properties in Peterborough", text: "One of my tenants stopped paying and I did not know where to start. Property Sauce handled it from the first missed payment: the reminders, the formal letters, the arrangement to pay, and they kept me informed at every step without dragging me into it. The arrears were cleared within three months and the tenant is still there and paying on time. Calm, methodical and fair to everyone." },
  { id: 9, name: "Jamal", who: "sold a block of seventeen flats in Doncaster", text: "I needed to sell a block of seventeen flats in Doncaster quickly and did not want the uncertainty of the open market. Property Sauce viewed it within days, made an offer with proof of funds, and completed in seven weeks exactly as agreed. No chain, no renegotiation, no surprises. If you need a clean sale from a buyer who knows what they are looking at, talk to them." },
  { id: 10, name: "Janet", who: "HMO landlord in South Yorkshire", text: "Licensed HMOs come with a long list of things that must be right and inspected. Property Sauce manage my five-bedroom HMO in South Yorkshire and keep on top of the licence conditions, the fire safety checks, the room-by-room tenancies and the turnover of tenants. The portal shows every certificate with its expiry date. I sleep better knowing nothing is going to lapse." },
  { id: 11, name: "James", who: "one flat in Walthamstow", text: "My flat in Walthamstow needed a full refurbishment between tenants. Property Sauce arranged the quotes, managed the contractors, sent me photos as it went along and had it relet at a higher rent within two weeks of the work finishing. The whole job came in on the budget they gave me. They treat the property as if it were their own." },
  { id: 12, name: "Francis", who: "seven properties in London, client since 2017", text: "Property Sauce have managed my properties in London for nine years. In that time I have had steady tenants, rent paid on time, and every certificate renewed without my having to remember it. The new portal is the best thing they have done: I can see each property's score, the rent history and every document in one place. I recommend them to any landlord who wants it done properly." },
];

const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

export function renderTestimonials(spec) {
  const list = spec.trim() === "all" ? testimonials : spec.split(",").map((n) => testimonials.find((t) => t.id === Number(n.trim()))).filter(Boolean);
  return `<div class="quotes">${list.map((t, i) => `<figure class="quote" data-reveal style="--d:${(i % 3) * 80}ms">
    <blockquote><p>${esc(t.text)}</p></blockquote>
    <figcaption><strong>${esc(t.name)}</strong><span>${esc(t.who)}</span></figcaption>
  </figure>`).join("")}</div>`;
}
